# Generated by Django 4.1.4 on 2023-02-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_product_favourite_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='product_qty',
            new_name='product',
        ),
    ]
