# Generated by Django 4.1.4 on 2023-03-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_product_qty_favourite_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='User',
        ),
    ]
