# Generated by Django 4.1.4 on 2023-03-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_user_cart_user_rename_user_favourite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='User',
            new_name='user',
        ),
    ]
