# Generated by Django 4.1.4 on 2023-03-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
